// Code generated by go generate; DO NOT EDIT.
package Buttons

const (
	Backwards      = 63243
	Blue           = 63267
	ChangeLanguage = 61470
	ChannelDown    = 63236
	ChannelUp      = 63237
	Down           = 40
	Esc            = 63274
	Favorite       = 61466
	Forwards       = 63244
	Green          = 63265
	Info           = 63273
	LC             = 63271
	Left           = 37
	Menu           = 63270
	Messages       = 61498
	Pause          = 63241
	Play           = 63241
	Power          = 63232
	Record         = 63242
	Red            = 63264
	Right          = 39
	Select         = 13
	Stop           = 63238
	Up             = 38
	Yellow         = 63266
)
