// Code generated by go generate; DO NOT EDIT.
package HotRemote

import "github.com/yakiroren/hotremote/buttons"

func (s *Session) PressBackwards() {
	s.Press(Buttons.Backwards)
}

func (s *Session) PressBlue() {
	s.Press(Buttons.Blue)
}

func (s *Session) PressChangeLanguage() {
	s.Press(Buttons.ChangeLanguage)
}

func (s *Session) PressChannelDown() {
	s.Press(Buttons.ChannelDown)
}

func (s *Session) PressChannelUp() {
	s.Press(Buttons.ChannelUp)
}

func (s *Session) PressDown() {
	s.Press(Buttons.Down)
}

func (s *Session) PressEsc() {
	s.Press(Buttons.Esc)
}

func (s *Session) PressFavorite() {
	s.Press(Buttons.Favorite)
}

func (s *Session) PressForwards() {
	s.Press(Buttons.Forwards)
}

func (s *Session) PressGreen() {
	s.Press(Buttons.Green)
}

func (s *Session) PressInfo() {
	s.Press(Buttons.Info)
}

func (s *Session) PressLC() {
	s.Press(Buttons.LC)
}

func (s *Session) PressLeft() {
	s.Press(Buttons.Left)
}

func (s *Session) PressMenu() {
	s.Press(Buttons.Menu)
}

func (s *Session) PressMessages() {
	s.Press(Buttons.Messages)
}

func (s *Session) PressPause() {
	s.Press(Buttons.Pause)
}

func (s *Session) PressPlay() {
	s.Press(Buttons.Play)
}

func (s *Session) PressPower() {
	s.Press(Buttons.Power)
}

func (s *Session) PressRecord() {
	s.Press(Buttons.Record)
}

func (s *Session) PressRed() {
	s.Press(Buttons.Red)
}

func (s *Session) PressRight() {
	s.Press(Buttons.Right)
}

func (s *Session) PressSelect() {
	s.Press(Buttons.Select)
}

func (s *Session) PressStop() {
	s.Press(Buttons.Stop)
}

func (s *Session) PressUp() {
	s.Press(Buttons.Up)
}

func (s *Session) PressYellow() {
	s.Press(Buttons.Yellow)
}
