// Package HotRemote Code generated by go generate; DO NOT EDIT.
package HotRemote

const (
	Backwards = 63243
	Blue = 63267
	ChangeLanguage = 61470
	ChannelDown = 63236
	ChannelUp = 63237
	Down = 40
	Esc = 63274
	Favorite = 61466
	Forwards = 63244
	Green = 63265
	Info = 63273
	LC = 63271
	Left = 37
	MENU = 63270
	Pause = 63241
	PersonalMessages = 61498
	Play = 63241
	Power = 63232
	Record = 63242
	Red = 63264
	Right = 39
	Select = 13
	Stop = 63238
	Up = 38
	Yellow = 63266
)

func (s *Session) Backwards() {
	s.ButtonPress(Backwards)
}

func (s *Session) Blue() {
	s.ButtonPress(Blue)
}

func (s *Session) ChangeLanguage() {
	s.ButtonPress(ChangeLanguage)
}

func (s *Session) ChannelDown() {
	s.ButtonPress(ChannelDown)
}

func (s *Session) ChannelUp() {
	s.ButtonPress(ChannelUp)
}

func (s *Session) Down() {
	s.ButtonPress(Down)
}

func (s *Session) Esc() {
	s.ButtonPress(Esc)
}

func (s *Session) Favorite() {
	s.ButtonPress(Favorite)
}

func (s *Session) Forwards() {
	s.ButtonPress(Forwards)
}

func (s *Session) Green() {
	s.ButtonPress(Green)
}

func (s *Session) Info() {
	s.ButtonPress(Info)
}

func (s *Session) LC() {
	s.ButtonPress(LC)
}

func (s *Session) Left() {
	s.ButtonPress(Left)
}

func (s *Session) MENU() {
	s.ButtonPress(MENU)
}

func (s *Session) Pause() {
	s.ButtonPress(Pause)
}

func (s *Session) PersonalMessages() {
	s.ButtonPress(PersonalMessages)
}

func (s *Session) Play() {
	s.ButtonPress(Play)
}

func (s *Session) Power() {
	s.ButtonPress(Power)
}

func (s *Session) Record() {
	s.ButtonPress(Record)
}

func (s *Session) Red() {
	s.ButtonPress(Red)
}

func (s *Session) Right() {
	s.ButtonPress(Right)
}

func (s *Session) Select() {
	s.ButtonPress(Select)
}

func (s *Session) Stop() {
	s.ButtonPress(Stop)
}

func (s *Session) Up() {
	s.ButtonPress(Up)
}

func (s *Session) Yellow() {
	s.ButtonPress(Yellow)
}

