// Package HotRemote Code generated by go generate; DO NOT EDIT.
package HotRemote

func (s *Session) VOD() {
	s.client.CustomEvent(s.targetBox, "63281", "1,zapdigit")
}

func (s *Session) Search() {
	s.client.CustomEvent(s.targetBox, "", "BasicSearch")
}

