// Code generated by go generate; DO NOT EDIT.
package HotRemote

func (s *Session) OpenVOD() {
	s.client.CustomEvent(s.targetBox, "63281", "1,zapdigit")
}

func (s *Session) OpenSearch() {
	s.client.CustomEvent(s.targetBox, "", "BasicSearch")
}
